// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	reportStartupPhase: (phase: StartupPhase) => __TAURI_INVOKE<null>("report_startup_phase", { phase }),
	getStartupPhase: () => __TAURI_INVOKE<StartupPhase>("get_startup_phase"),
	finishStartup: () => __TAURI_INVOKE<null>("finish_startup"),
	listMods: (gameId: number, params: {
	query: string | null,
	limit: number | null,
	sort: string | null,
	category_id: number | null,
	page: number | null,
	ids: number[] | null,
	tags: number[] | null,
	block_tags: number[] | null,
} | null) => __TAURI_INVOKE<unknown>("list_mods", { gameId, params }),
	getMod: (id: number) => __TAURI_INVOKE<unknown>("get_mod", { id }),
	listModFiles: (modId: number) => __TAURI_INVOKE<unknown>("list_mod_files", { modId }),
	listModLinks: (modId: number) => __TAURI_INVOKE<unknown>("list_mod_links", { modId }),
	listCategories: (gameId: number) => __TAURI_INVOKE<unknown>("list_categories", { gameId }),
	nexusSearchMods: (gameId: string, query: string, sort: string, offset: number | null) => __TAURI_INVOKE<unknown>("nexus_search_mods", { gameId, query, sort, offset }),
	nexusOauthStart: () => __TAURI_INVOKE<void>("nexus_oauth_start"),
	nexusOauthSignedIn: () => __TAURI_INVOKE<boolean>("nexus_oauth_signed_in"),
	nexusOauthSignOut: () => __TAURI_INVOKE<void>("nexus_oauth_sign_out"),
	listTags: (gameId: number) => __TAURI_INVOKE<unknown>("list_tags", { gameId }),
	setDiscordPresenceEnabled: (enabled: boolean) => __TAURI_INVOKE<void>("set_discord_presence_enabled", { enabled }),
	updateDiscordPresence: (game: string) => __TAURI_INVOKE<void>("update_discord_presence", { game }),
	/**
	 *  Returns a backwards-compatible flat view of PD3 settings for the renderer.
	 *  Commit 4 will switch callers to `get_game_settings` once the game switcher lands.
	 */
	getSettings: () => __TAURI_INVOKE<unknown>("get_settings"),
	getGameSettings: (gameId: string) => __TAURI_INVOKE<GameSettings>("get_game_settings", { gameId }),
	setLauncher: (gameId: string | null, launcher: string) => __TAURI_INVOKE<void>("set_launcher", { gameId, launcher }),
	setLaunchOptions: (gameId: string | null, launchOptions: string) => __TAURI_INVOKE<void>("set_launch_options", { gameId, launchOptions }),
	setCrimebossInstallMode: (mode: string) => __TAURI_INVOKE<void>("set_crimeboss_install_mode", { mode }),
	setSuppressCrashReporter: (gameId: string | null, suppress: boolean) => __TAURI_INVOKE<void>("set_suppress_crash_reporter", { gameId, suppress }),
	setSkipFileopenlogWarning: (skip: boolean) => __TAURI_INVOKE<void>("set_skip_fileopenlog_warning", { skip }),
	dismissDepsWarning: (modId: number) => __TAURI_INVOKE<void>("dismiss_deps_warning", { modId }),
	/**
	 *  Counts a successful mod install toward the one-time "star us on GitHub"
	 *  prompt. When the milestone is reached in a clean session, the shown flag is
	 *  persisted *before* the renderer displays anything (write-on-show), so the
	 *  prompt can never fire twice while settings.json survives.
	 */
	recordSuccessfulInstall: (cleanSession: boolean) => __TAURI_INVOKE<void>("record_successful_install", { cleanSession }),
	/**  Current analytics consent: `None` = not yet asked, `Some(true/false)` = chosen. */
	getAnalyticsConsent: () => __TAURI_INVOKE<boolean | null>("get_analytics_consent"),
	/**
	 *  Records the user's explicit analytics choice. Generates the anonymous install
	 *  ID lazily on first opt-in, so a user who never enables analytics never gets one.
	 */
	setAnalyticsConsent: (enabled: boolean) => __TAURI_INVOKE<void>("set_analytics_consent", { enabled }),
	/**
	 *  Renderer-origin events route through here; Rust-native events call `track`
	 *  directly. Both share the consent gate in `send_event`.
	 */
	trackEvent: (name: string, params: unknown | null) => __TAURI_INVOKE<void>("track_event", { name, params }),
	getInstalled: (gameId: string | null) => __TAURI_INVOKE<InstalledResponse_Serialize>("get_installed", { gameId }),
	installMod: (modId: number, gamePath: string, folderId: string | null, gameId: string | null) => __TAURI_INVOKE<null>("install_mod", { modId, gamePath, folderId, gameId }),
	installFile: (modId: number, modName: string, fileId: number, downloadUrl: string, fileType: string, modVersion: string, gamePath: string, gameId: string | null) => __TAURI_INVOKE<null>("install_file", { modId, modName, fileId, downloadUrl, fileType, modVersion, gamePath, gameId }),
	/**
	 *  Installs a mod from a local file the user dropped onto the window (Explorer drag-drop).
	 *  The file carries no modworkshop identity, so it is installed as an unidentified entry
	 *  (negative id, "unknown" version) exactly like an ambiently-discovered pak — `get_installed`'s
	 *  SHA256 upgrade resolves its real identity on the next refresh. The dropped file is copied into
	 *  temp first so resolution/cleanup never touches the user's original.
	 */
	installDroppedFile: (path: string, gamePath: string, folderId: string | null, gameId: string | null) => __TAURI_INVOKE<null>("install_dropped_file", { path, gamePath, folderId, gameId }),
	installFromZipEntry: (args: InstallFromZipEntryArgs) => __TAURI_INVOKE<null>("install_from_zip_entry", { args }),
	/**
	 *  Installs a Crime Boss archive whose content has no enclosing folder (every entry sits at the
	 *  zip root) — the renderer reaches this after a user confirms a `CB_FLAT_ARCHIVE` dialog. There's
	 *  only one possible destination (the primary `mods` target, which blanket-accepts any directory),
	 *  so unlike `install_from_zip_entry` there's no entry to pick: the whole archive is extracted flat
	 *  and installed as a single `mods/<name>` folder named from the mod's display name.
	 */
	installCbFlatArchive: (zipPath: string, modId: number, modName: string, fileId: number, fileType: string, modVersion: string, gamePath: string, folderId: string | null) => __TAURI_INVOKE<null>("install_cb_flat_archive", { zipPath, modId, modName, fileId, fileType, modVersion, gamePath, folderId }),
	installHostPack: (args: InstallHostPackArgs) => __TAURI_INVOKE<null>("install_host_pack", { args }),
	deleteTempFile: (path: string) => __TAURI_INVOKE<void>("delete_temp_file", { path }),
	uninstallMod: (gamePath: string, uid: string, gameId: string | null) => __TAURI_INVOKE<void>("uninstall_mod", { gamePath, uid, gameId }),
	enableMod: (gamePath: string, uid: string, gameId: string | null) => __TAURI_INVOKE<void>("enable_mod", { gamePath, uid, gameId }),
	disableMod: (gamePath: string, uid: string, gameId: string | null) => __TAURI_INVOKE<void>("disable_mod", { gamePath, uid, gameId }),
	moveCrimebossModTarget: (gamePath: string, uid: string) => __TAURI_INVOKE<null>("move_crimeboss_mod_target", { gamePath, uid }),
	reorderInFolder: (gamePath: string, folderId: string | null, orderedUids: string[], gameId: string | null) => __TAURI_INVOKE<void>("reorder_in_folder", { gamePath, folderId, orderedUids, gameId }),
	moveToFolder: (gamePath: string, uid: string, targetFolderId: string | null, targetPosition: number, gameId: string | null) => __TAURI_INVOKE<void>("move_to_folder", { gamePath, uid, targetFolderId, targetPosition, gameId }),
	reorderChildren: (gamePath: string, parentId: string | null, items: TopLevelItem[], gameId: string | null) => __TAURI_INVOKE<void>("reorder_children", { gamePath, parentId, items, gameId }),
	moveFolder: (gamePath: string, folderId: string, targetParentId: string | null, gameId: string | null) => __TAURI_INVOKE<void>("move_folder", { gamePath, folderId, targetParentId, gameId }),
	createFolder: (gamePath: string, displayName: string, parentId: string | null, gameId: string | null) => __TAURI_INVOKE<ModFolder>("create_folder", { gamePath, displayName, parentId, gameId }),
	renameFolder: (gamePath: string, folderId: string, displayName: string, gameId: string | null) => __TAURI_INVOKE<void>("rename_folder", { gamePath, folderId, displayName, gameId }),
	deleteFolder: (gamePath: string, folderId: string, gameId: string | null) => __TAURI_INVOKE<void>("delete_folder", { gamePath, folderId, gameId }),
	openModsFolder: (gameId: string | null) => __TAURI_INVOKE<void>("open_mods_folder", { gameId }),
	listModFolders: (gameId: string | null) => __TAURI_INVOKE<ModFolderInfo[]>("list_mod_folders", { gameId }),
	openModFolder: (gameId: string | null, tag: string) => __TAURI_INVOKE<void>("open_mod_folder", { gameId, tag }),
	checkSuperblt: (gamePath: string) => __TAURI_INVOKE<boolean>("check_superblt", { gamePath }),
	/**
	 *  Installs the loader DLL into the game root. The basemod (mods/base) is
	 *  fetched by the loader itself: on next launch it prompts the user to
	 *  download it if missing.
	 */
	installSuperblt: (gamePath: string) => __TAURI_INVOKE<null>("install_superblt", { gamePath }),
	isPd2Diesel3: (gamePath: string) => __TAURI_INVOKE<boolean>("is_pd2_diesel3", { gamePath }),
	checkPdthOverrides: (gamePath: string) => __TAURI_INVOKE<boolean>("check_pdth_overrides", { gamePath }),
	installPdthOverrides: (gamePath: string) => __TAURI_INVOKE<null>("install_pdth_overrides", { gamePath }),
	checkDahm: (gamePath: string) => __TAURI_INVOKE<boolean>("check_dahm", { gamePath }),
	/**  Downloads the DAHM ZIP and extracts all entries flat into the game root. */
	installDahm: (gamePath: string) => __TAURI_INVOKE<null>("install_dahm", { gamePath }),
	checkRaidSuperblt: (gamePath: string) => __TAURI_INVOKE<boolean>("check_raid_superblt", { gamePath }),
	/**
	 *  Downloads the RAID-SuperBLT zip and extracts it whole into the game root.
	 *  Unlike PD2's SuperBLT (DLL-only zip, basemod fetched by the loader on next
	 *  launch), the RAID zip ships the basemod inside, so a full extraction is
	 *  the complete install.
	 */
	installRaidSuperblt: (gamePath: string) => __TAURI_INVOKE<null>("install_raid_superblt", { gamePath }),
	checkUe4ss: (gamePath: string, gameId: string | null) => __TAURI_INVOKE<boolean>("check_ue4ss", { gamePath, gameId }),
	installedLaunchers: (gameId: string | null) => __TAURI_INVOKE<string[]>("installed_launchers", { gameId }),
	configureGamePath: (gameId: string | null, gamePath: string | null) => __TAURI_INVOKE<void>("configure_game_path", { gameId, gamePath }),
	pickFolder: (defaultPath: string | null) => __TAURI_INVOKE<string | null>("pick_folder", { defaultPath }),
	launchGame: (gameId: string | null) => __TAURI_INVOKE<void>("launch_game", { gameId }),
	launchWithoutMods: (gameId: string | null) => __TAURI_INVOKE<null>("launch_without_mods", { gameId }),
	restoreMods: (gameId: string | null) => __TAURI_INVOKE<null>("restore_mods", { gameId }),
	isGameRunning: (gameId: string | null) => __TAURI_INVOKE<boolean>("is_game_running", { gameId }),
	stopGame: (gameId: string | null) => __TAURI_INVOKE<void>("stop_game", { gameId }),
	shellOpenExternal: (url: string) => __TAURI_INVOKE<void>("shell_open_external", { url }),
	shellOpenPath: (path: string) => __TAURI_INVOKE<void>("shell_open_path", { path }),
	openLogFile: () => __TAURI_INVOKE<void>("open_log_file"),
	openDataFolder: () => __TAURI_INVOKE<void>("open_data_folder"),
	openAppFolder: () => __TAURI_INVOKE<void>("open_app_folder"),
	checkForUpdate: () => __TAURI_INVOKE<null>("check_for_update"),
	downloadUpdate: () => __TAURI_INVOKE<null>("download_update"),
	installUpdate: () => __TAURI_INVOKE<null>("install_update"),
	/**
	 *  Caches an image and returns the cache filename for the renderer to build its
	 *  thumb:// URL from. Default: the pre-generated small variant
	 *  (thumbnail_{file}, ~10-20x smaller than the original, which can be multiple
	 *  MB), falling back to the original for old images without one
	 *  (has_thumb: false). With full = true: the original, cached under
	 *  {filename}, used by the detail page (banner, lightbox), where the CDN's
	 *  missing cache headers would otherwise cost a revalidation round-trip per view.
	 */
	getThumbnail: (filename: string, full: boolean | null) => __TAURI_INVOKE<string>("get_thumbnail", { filename, full }),
	getIndexModFiles: (modId: number, gameId: string | null) => __TAURI_INVOKE<IndexModFile[]>("get_index_mod_files", { modId, gameId }),
	/**
	 *  Page 1 only — this is the cached, TTL-backed entry point used on first
	 *  load and by the Refresh button.
	 */
	fetchNews: (gameId: string | null) => __TAURI_INVOKE<NewsResult>("fetch_news", { gameId }),
	refreshNews: (gameId: string | null) => __TAURI_INVOKE<NewsResult>("refresh_news", { gameId }),
	/**
	 *  Pages other than 1 — fetched on demand, never cached (the disk cache
	 *  exists to make the default page-1 view instant, not to mirror the whole
	 *  site).
	 */
	fetchNewsPage: (gameId: string | null, page: number) => __TAURI_INVOKE<NewsResult>("fetch_news_page", { gameId, page }),
	getStorageUsage: () => __TAURI_INVOKE<StorageUsage>("get_storage_usage"),
	clearThumbnailCache: () => __TAURI_INVOKE<number>("clear_thumbnail_cache"),
	clearIndexCache: () => __TAURI_INVOKE<number>("clear_index_cache"),
	clearNewsCache: () => __TAURI_INVOKE<number>("clear_news_cache"),
	/**
	 *  Factory-resets settings.json to defaults: clears every configured game path,
	 *  launcher choice, launch options, analytics consent + id, and all other
	 *  preferences. Does not touch installed mods, game files, or the on-disk caches.
	 */
	resetAppSettings: () => __TAURI_INVOKE<void>("reset_app_settings"),
};

/* Types */
export type GameSettings = {
	gamePath: string | null,
	launcher: string | null,
	launchOptions: string | null,
	suppressCrashReporter: boolean | null,
	crimebossInstallMode: string | null,
};

export type IndexModFile = {
	fileRemoteId: number,
	entryName: string,
};

export type InstallFromZipEntryArgs = {
	zipPath: string,
	entryName: string,
	modId: number,
	modName: string,
	fileId: number,
	fileType: string,
	modVersion: string,
	gamePath: string,
	folderId: string | null,
	gameId: string | null,
	locationTag: string | null,
	entryKind: string | null,
};

/**
 *  Installs a content set from an already-downloaded archive into a host mod's folder (e.g. a
 *  Menu Backgrounds set into `mods/Menu Backgrounds/Assets/`). The renderer reaches this after a
 *  `HOST_MOD_PACK` sentinel; the zip is left in place for multi-set installs (caller deletes it).
 */
export type InstallHostPackArgs = {
	zipPath: string,
	entryName: string,
	modId: number,
	modName: string,
	fileId: number,
	fileType: string,
	modVersion: string,
	gamePath: string,
	hostModId: number,
	hostSubpath: string,
	gameId: string | null,
};

export type InstalledMod = InstalledMod_Serialize | InstalledMod_Deserialize;

export type InstalledMod_Deserialize = {
	uid?: string,
	id: number,
	name: string,
	version: string,
	filename: string,
	enabled: boolean,
	installedAt: string,
	source?: string,
	author?: string | null,
	thumbnailUrl?: string | null,
	fileId: number | null,
	fileType: string | null,
	sha256: string | null,
	priority: number | null,
	missing: boolean | null,
	folderId?: string | null,
	archiveBroken?: boolean | null,
	location?: string | null,
};

export type InstalledMod_Serialize = {
	uid: string,
	id: number,
	name: string,
	version: string,
	filename: string,
	enabled: boolean,
	installedAt: string,
	source: string,
	author?: string | null,
	thumbnailUrl?: string | null,
	fileId?: number | null,
	fileType?: string | null,
	sha256?: string | null,
	priority?: number | null,
	missing?: boolean | null,
	folderId?: string | null,
	archiveBroken?: boolean | null,
	location?: string | null,
};

export type InstalledResponse = InstalledResponse_Serialize | InstalledResponse_Deserialize;

export type InstalledResponse_Deserialize = {
	mods: InstalledMod_Deserialize[],
	folders: ModFolder[],
	modsHidden: boolean,
};

export type InstalledResponse_Serialize = {
	mods: InstalledMod_Serialize[],
	folders: ModFolder[],
	modsHidden: boolean,
};

export type ListModsParams = {
	query: string | null,
	limit: number | null,
	sort: string | null,
	category_id: number | null,
	page: number | null,
	ids: number[] | null,
	tags: number[] | null,
	block_tags: number[] | null,
};

export type ModFolder = {
	id: string,
	diskName: string,
	displayName: string,
	priority: number,
	parentId: string | null,
};

export type ModFolderInfo = {
	tag: string,
	labelKey: string,
};

export type NewsItem = {
	title: string,
	url: string,
	date: string,
	excerpt: string,
	image: string | null,
	categories: string[],
};

export type NewsResult = {
	items: NewsItem[],
	totalPages: number,
};

export type StartupPhase = "prepare" | "interface" | "game" | "mods" | "ready" | "error";

/**
 *  Sizes in bytes of the app's regenerable on-disk caches, for the Settings
 *  storage view. settings.json (user data) and the renderer's localStorage
 *  mod-metadata cache are measured and cleared elsewhere.
 */
export type StorageUsage = {
	thumbnails: number,
	indexDb: number,
	news: number,
};

export type TopLevelItem = { type: "folder"; id: string } | { type: "mod"; id: string };

